language: csharp
solution: ./Beaker.Core/Beaker.Core.sln
 
install:
  - sudo apt-get install nunit-console
  - nuget restore ./Beaker.Core/Beaker.Core.sln
 
script:
  - xbuild ./Beaker.Core/Beaker.Core.sln
  - nunit-console ./Beaker.Core.Test/Beaker.Core.Test/bin/Debug/Beaker.Core.Test.dll

